name: timeseriesbook
channels:
- defaults
- conda-forge
dependencies:
- python=3.7.9
- pandas=1.1.1
- matplotlib=3.1.1
- scikit-learn=0.23.2
- statsmodels=0.12.0
- seaborn=0.10.1
- jupyterlab
- pip
- pip:
  - ipykernel
  - tensorflow==2.3.0
  - pandas-datareader==0.9.0
